apiVersion: v1
kind: Service
metadata:
  name: eventstream-server
  namespace: logevents
  labels:
    name: eventstream-db
spec:
  selector:
    name: eventstream-db
  ports:
  - name: db
    port: 9200
    targetPort: es
  type: LoadBalancer
