apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: eventstream-db
    namespace: logevents
  name: eventstream-db
spec:
  replicas: 4
  selector:
    name: eventstream-db
  template:
    metadata:
      labels:
         name: eventstream-db
    spec:
      containers:
      - name: es
        image: kubernetes/elasticsearch:1.0
        env:
          - name: "CLUSTER_NAME"
            value: "logevents-db"
          - name: "SELECTOR"
            value: "name=eventstream-db"
          - name: "NAMESPACE"
            value: "logevents"
        ports:
        - name: es
          containerPort: 9200
        - name: es-transport
          containerPort: 9300
        volumeMounts:
        - name: apiserver-secret
          mountPath: /etc/apiserver-secret
          readOnly: true
      volumes:
      - name: apiserver-secret
        secret:
          secretName: apiserver-secret
